name: Env and Deploy
on:
    push:
        branches: [develop, main]
env:
    name: spotify-ml-ui
    region: us-east-1
jobs:
    env:
      name: Load environment vars from .env files
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Dev vars
          if: contains(github.ref, 'develop')
          run: for v in `cat .github/workflows/dev.env` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
        - name: Prod vars
          if: contains(github.ref, 'main')
          run: for v in `cat .github/workflows/prod.env`; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
      outputs:
        environment: ${{env.environment}}
        region: ${{env.region}}
    deploy:
      name: Deploy|${{needs.env.outputs.environment}}
      needs: env
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Configure AWS Credentials
          id: creds
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: ${{needs.env.outputs.region}}
        - name: Set up Nodejs
          uses: actions/setup-node@v2-beta
          with:
            node-version: '12'
        - name: Install node modules
          run: npm install
        - name: Serverless Deploy
          uses: serverless/github-action@v1.53.0
          with:
            args: -c "serverless deploy --stage ${{needs.env.outputs.environment}}"
            entrypoint: /bin/bash
          env:
            environment: ${{needs.env.outputs.environment}}
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            SPOTIPY_CLIENT_ID: ${{secrets.SPOTIPY_CLIENT_ID}}
            SPOTIPY_CLIENT_SECRET: ${{secrets.SPOTIPY_CLIENT_SECRET}}
            SPOTIPY_REDIRECT_URI: ${{secrets.SPOTIPY_REDIRECT_URI}}
        - name: Deploy static files to S3
          run: aws S3 sync app/ s3://${{needs.env.outputs.environment}}-spotify-ml-ui-bucket